In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn import tree
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
data = {
    'Age': [22, 25, 30, 35, 40, 50],
    'Income': ['Low', 'Medium', 'High', 'Low', 'High', 'Medium'],
    'Buys_Product': ['No', 'Yes', 'Yes', 'No', 'Yes', 'No']
}

In [3]:
df=pd.DataFrame(data)

In [4]:
label_encoder_age = LabelEncoder()
label_encoder_income = LabelEncoder()
label_encoder_target = LabelEncoder()

In [5]:
df['Age']=label_encoder_age.fit_transform(df['Age'])
df['Income']=label_encoder_income.fit_transform(df['Income'])
df['Buys_Product']=label_encoder_target.fit_transform(df['Buys_Product'])

In [6]:
X = df[['Age', 'Income']].values
y = df['Buys_Product'].values

In [7]:
X

array([[0, 1],
       [1, 2],
       [2, 0],
       [3, 1],
       [4, 0],
       [5, 2]], dtype=int64)

In [8]:
y

array([0, 1, 1, 0, 1, 0])

In [9]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
x_train

array([[5, 2],
       [2, 0],
       [4, 0],
       [3, 1]], dtype=int64)

In [11]:
x_test

array([[0, 1],
       [1, 2]], dtype=int64)

In [12]:
y_train

array([0, 1, 1, 0])

In [13]:
y_test

array([0, 1])

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy')
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [16]:
y_pred=classifier.predict(x_test)

In [17]:
y_pred

array([0, 0])

In [18]:
new_sample = [[2, 0]] 
predicted = classifier.predict(new_sample)
print("Predicted class:", label_encoder_target.inverse_transform(predicted))

Predicted class: ['Yes']


In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
fd=pd.read_csv('airlines_delay.csv')
fd

Flight    Time  Length Airline AirportFrom AirportTo  DayOfWeek  Class
0       2313.0  1296.0   141.0      DL         ATL       HOU          1      0
1       6948.0   360.0   146.0      OO         COS       ORD          4      0
2       1247.0  1170.0   143.0      B6         BOS       CLT          3      0
3         31.0  1410.0   344.0      US         OGG       PHX          6      0
4        563.0   692.0    98.0      FL         BMI       ATL          4      0
...        ...     ...     ...     ...         ...       ...        ...    ...
539377  6973.0   530.0    72.0      OO         GEG       SEA          5      1
539378  1264.0   560.0   115.0      WN         LAS       DEN          4      1
539379  5209.0   827.0    74.0      EV         CAE       ATL          2      1
539380   607.0   715.0    65.0      WN         BWI       BUF          4      1
539381  6377.0   770.0    55.0      OO         CPR       DEN          2      1

[539382 rows x 8 columns]

In [20]:
fd.isnull().sum()

Flight         0
Time           0
Length         0
Airline        0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Class          0
dtype: int64

In [21]:
label_encoder_flight=LabelEncoder()
label_encoder_time=LabelEncoder()
label_encoder_length=LabelEncoder()
label_encoder_airline=LabelEncoder()
label_encoder_airportfrom=LabelEncoder()
label_encoder_airportto=LabelEncoder()
label_encoder_dayofweek=LabelEncoder()

In [22]:
fd['Flight']=label_encoder_flight.fit_transform(fd['Flight'])
fd['Flight']

0         2308
1         6198
2         1243
3           29
4          561
          ... 
539377    6223
539378    1260
539379    5004
539380     605
539381    5664
Name: Flight, Length: 539382, dtype: int64

In [23]:
fd['Time']=label_encoder_time.fit_transform(fd['Time'])
fd['Time']

0         1006
1           70
2          880
3         1112
4          402
          ... 
539377     240
539378     270
539379     537
539380     425
539381     480
Name: Time, Length: 539382, dtype: int64

In [24]:
fd['Length']=label_encoder_length.fit_transform(fd['Length'])
fd['Length']

0         119
1         124
2         121
3         322
4          76
         ... 
539377     50
539378     93
539379     52
539380     43
539381     33
Name: Length, Length: 539382, dtype: int64

In [25]:
fd['Airline']=label_encoder_airline.fit_transform(fd['Airline'])
fd['Airline']

0          5
1         12
2          3
3         14
4          8
          ..
539377    12
539378    15
539379     6
539380    15
539381    12
Name: Airline, Length: 539382, dtype: int32

In [26]:
fd['AirportFrom']=label_encoder_airportfrom.fit_transform(fd['AirportFrom'])
fd['AirportFrom']

0          16
1          65
2          35
3         203
4          32
         ... 
539377    111
539378    153
539379     47
539380     45
539381     67
Name: AirportFrom, Length: 539382, dtype: int32

In [27]:
fd['AirportTo']=label_encoder_airportto.fit_transform(fd['AirportTo'])
fd['AirportTo']

0         129
1         208
2          60
3         217
4          16
         ... 
539377    252
539378     79
539379     16
539380     43
539381     79
Name: AirportTo, Length: 539382, dtype: int32

In [28]:
x=fd.drop('Class', axis=1).values
y=fd['Class'].values

In [29]:
x

array([[2308, 1006,  119, ...,   16,  129,    1],
       [6198,   70,  124, ...,   65,  208,    4],
       [1243,  880,  121, ...,   35,   60,    3],
       ...,
       [5004,  537,   52, ...,   47,   16,    2],
       [ 605,  425,   43, ...,   45,   43,    4],
       [5664,  480,   33, ...,   67,   79,    2]], dtype=int64)

In [30]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [31]:
x_train, x_test, y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=32)

In [32]:
x_train

array([[  59,  523,   24, ...,   50,   14,    6],
       [3831,  245,  148, ...,  252,  217,    5],
       [1761,  235,  113, ...,  261,  252,    2],
       ...,
       [5806,  789,   55, ...,  258,  154,    7],
       [ 839,  330,  160, ...,  104,   35,    2],
       [6545,  300,   64, ...,  261,  255,    4]], dtype=int64)

In [33]:
x_test

array([[ 281,  842,  130, ...,   79,  111,    6],
       [3705,  635,   44, ...,   85,  221,    3],
       [4216,  290,   98, ...,  233,  277,    7],
       ...,
       [ 790,  370,   98, ...,  175,  146,    3],
       [4028,  100,   49, ...,   27,  177,    4],
       [1390,  575,  148, ...,  277,   80,    2]], dtype=int64)

In [34]:
y_train

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [35]:
y_test

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
classifier=RandomForestClassifier(n_estimators=10,criterion='entropy')
classifier.fit(x_train,y_train)
RandomForestClassifier(criterion='entropy', n_estimators=10)

RandomForestClassifier(criterion='entropy', n_estimators=10)